#+begin_export latex
The program \texttt{intersect} searches for homologous regions common to a
set of target genomes shared by two genomes.  \texttt{intersect} has hooks
for imports and the main function.
#+end_export
#+begin_src go <<intersect.go>>=
  package main
  import (
	  //<<Imports>>
  )
  func main(){
	  //<<Main function>>
  }
#+end_src
#+begin_export latex
In the main function, we declare the options, set the usage, parse the
options, run the \texttt{Intersect} function, and print the results.
#+end_export
#+begin_src go <<Main function>>=
  //<<Declare options>>
  //<<Set usage>>
  //<<Parse options>>
  //<<Run \texttt{Intersect}>>
  //<<Print the results>>
#+end_src
#+begin_export latex
The program \texttt{intersect} takes \texttt{fasta}-formatted target sequences
as input. There is one reference (subject) and a folder of other
targets that are considered queries. The user can set thresholds for
the shustring p-value and the fraction of intersecting nucleotides.
We also declare options for the output formatting, and toggling the
verbose mode. Finally, one can set the number of threads.
#+end_export
#+begin_src go <<Declare options>>=
  optR := flag.String("r", "", "reference sequence")

  optP := flag.Float64("p", 0.975,
	  "threshold p-value for a shustring length")

  optN := flag.Bool("n", false, "print segregating sites (Ns) " +
	  "in the output sequences")

  optF := flag.Float64("f", 1.0,
	  "intersection sensitivity threshold")

  optT := flag.Int("t", 1, "number of threads")
#+end_src
#+begin_export latex
We improt \texttt{flag}.
#+end_export
#+begin_src go <<Imports>>=
  "flag"
#+end_src
#+begin_export latex
The usage consists of three statements. The actual usage statement, an
explanation of the program’s purpose, and an example command.
#+end_export
#+begin_src go <<Set usage>>=
  u := "intersect [option]..."
  p := "Find common homologous regions in a set of genomes"
  e := "intersect -r subject.fna query1.fna query2.fna ..."
  clio.Usage(u, p, e)
#+end_src
#+begin_export latex
We import \texttt{clio}.
#+end_export
#+begin_src go <<Imports>>=
  "github.com/evolbioinf/clio"
#+end_src
#+begin_export latex
We parse the options and check the number of input files and the
reference. Then we read the reference's contigs and set parameters for
\texttt{Intersect}.
#+end_export
#+begin_src go <<Parse options>>=
  flag.Parse()
  //<<Check the reference>>
  //<<Read reference's contigs>>
  //<<Set parameters>>
#+end_src
#+begin_export latex
We import \texttt{fmt} and \texttt{os}.
#+end_export
#+begin_src go <<Imports>>=
  "fmt"
  "os"
#+end_src
#+begin_export latex
We check if the reference has been specified. If so, we check if it is
duplicated in the target directory.
#+end_export
#+begin_src go <<Check the reference>>=
  if *optR == "" {
	  fmt.Fprintf(os.Stderr,
		  "please specify the reference sequence\n")
	  os.Exit(1)
  }
#+end_src
#+begin_export latex
We read the reference's contigs from the specified file.
#+end_export
#+begin_src go <<Read reference's contigs>>=
  f, _ := os.Open(*optR)
  referenceContigs := fastautils.ReadAll(f)
  f.Close()
#+end_src
#+begin_export latex
We import \texttt{fastautils}.
#+end_export
#+begin_src go <<Imports>>=
  "github.com/ivantsers/fastautils"
#+end_src
#+begin_export latex
We interpret the parameter flags and create a \texttt{Parameters} struct.
#+end_export
#+begin_src go <<Set parameters>>=
  //<<Interpret *optP>>
  //<<Interpret *optF>>
  //<<Create a Parameters struct>>
#+end_src
#+begin_export latex
The shustring p-value $p$ is defined for $0 \le p \le 1$.
#+end_export
#+begin_src go <<Interpret *optP>>=
  if *optP > 1 || *optP < 0 {
	  fmt.Fprintf(os.Stderr,
		  "can't use %v as a sensitivity threshold\n",
		  *optF)
	  os.Exit(1)
  }
#+end_src
#+begin_export latex
The sensitivity threshold $f$ is defined as $0 < f \le 1$.
#+end_export
#+begin_src go <<Interpret *optF>>=
  if *optF > 1.0 || *optF <= 0.0 {
	  fmt.Fprintf(os.Stderr,
		  "can't use %v as a sensitivity threshold, " +
			  "please use a value in the interval (0,1]",
		  *optF)
	  os.Exit(1)
  }
#+end_src
#+begin_export latex
We initialize and populate a \texttt{Parameters} struct with the
interpreted parameters.
#+end_export
#+begin_src go <<Create a Parameters struct>>=
  parameters := chr.Parameters{
	  Reference:       referenceContigs,
	  QueryPaths:      flag.Args(),
	  Threshold:       *optF,
	  ShustrPval:      *optP,
	  PrintN:          *optN,
	  NumThreads:      *optT,
  }
#+end_src
#+begin_export latex
We import \texttt{chr}.
#+end_export
#+begin_src go <<Imports>>=
  "github.com/ivantsers/chr"
#+end_src
#+begin_export latex
We run the \texttt{Intersect} function with our parameters.
#+end_export
#+begin_src go <<Run \texttt{Intersect}>>=
  isc := chr.Intersect(parameters)
#+end_src
#+begin_export latex
We print the result. If the verbose mode is toggled, we report some
statistics in the \texttt{stderr}, the rest goes to \texttt{stdout}.
#+end_export
#+begin_src go <<Print the results>>=
  for _, seq := range(isc) {
	  fmt.Fprintf(os.Stdout, "%s\n", seq)
  }
#+end_src
